language: ruby
jdk:
- oraclejdk8
sudo: false
rvm:
- 2.3.1
before_install:
- openssl aes-256-cbc -K $encrypted_a796be79d2ec_key -iv $encrypted_a796be79d2ec_iv
  -in etc/secrets -out ../secrets.tar -d
- "(cd ../ && tar xvf secrets.tar)"
- chmod 600 ../release.asc
- gpg --import ../release.asc
install:
- rvm use 2.3.1
- gem install bundler
- bundle install
script: buildr clean package mcrt:publish_if_tagged
git:
  depth: false
env:
  global:
  - secure: Fl33HTdzGit0aqn7o7Kn5kCkfcG9s9+7z6ECKx3f55N7k3mCTv+8b8mgieu+yYvrgdgY5pwpc15iPfAm47cTIGEWdclaPtHDAL6bBIDgTyKj7bSYKmgdorojKCT2PLKwbuYD4CFfyrG4mERr1lK9Sm5zR+4+eKaIVakE+A3XPoLUBVTU3sIFuEEYj7Ny+948E0+aJiM9k9zspWIhkaGttHs1rdQSr0gMrKvi0A1cwRP5bluKBaLkFkKXJn8zXnZSyxFkzibjijFe92pNXJKN1azXFv9YZuXZnDq6gxESiWnUPArzinllVpktgFy93tJgr2DutYd1ytZLHGUqA0h/O5uUrugtdtCmVJfnoWqNT/lDCyTeskgOmtjl014ZwW7lGGSKUeeGc9iU69w4Cg5/VHzR6eGX76jyUGIB88hUu9+HQmdk40y2dJDX6Xtbv/fqURW2pAJHr4s/HV/cKNtSRE2GNciUCqTQX06c4Viju+HToKHgM1UJZAU4ns2CYzHGAbcxKQxsK1H8vNWRzDtap5HgULDiW5HUYnMayUuLYzR1gSzUP0QeMZcUnB/R76U/vz553r7ZP9IHFHjV/ljiVbhqriw2A1zsvKKbF5HvUpU+m6jRqNAQN1OlPmDdsIvwpubJYbGRXEtr9QpA+GkG+iTCJneT3wsb3I8tyJYVbeM=
  - secure: qrc6AdgLNX8b9hkMZvBfAmzpQ65IeKmhUoN5PDzTdabE7NjNDh4q3RhaLf7iHgYyz6ZWHvofynynJ9tmfDrIhkXu51fe0dnadm1jNgy3KGUd0s0CttHyA9xoa7vSPsMkcbKHysYBOuGtTaQArQIng8nTIhzGpCzl0pN4nUU5jjK0xTQ99Mmd3pX09W47DYPEtcmu3K/TGxcicU1bD54g3OU8Ub28rEUIGhEqHfWEDVdDwpXsdRZni82dsnOVz0gNGnpmjtvy6Jm7plPsjOqLtS/gfuSAuTTIsECvuCz66mcbkMqbUBracOySTwHjDu4xUjk1SV1vmlc3IAx/azVxkdM8NZiMWVR8BTrqCGhU6U0dtTElKQWZEpNb0CJLmRVBBlar8vQXr9ezfqU/hg99dhaMs1d9Edf6XPoqQjm4DXhSn4QhAsX3bivi2K6mMvR5omnn8nsv0AMn97/eqdG3AWKhjXeEiUPvhfrg8laxFt19At4SPr3DMgcA4iNzOVCjFFqGEFqsSoUB412qqWV+NdjGpqdbmPJCH7zhqMvM5wNCBv6jeQDeQBKj/HeMywd8P6EKo51R3wO23Hm0r1sYYMCVoK4NKrrKquk8k4sYyD4p5iI/PsePucrjQd/sfZKWNn89ybjk9nz/paHImQGkzePL90IrGRhlaGdRReJ6ofg=
  - secure: ASdU9Az1VH0Za6bGEKad/Qg6YiLMn6vjsQRKf7T5+iJdOgmMz5TGXx4Xu4HpLUsfZJ1exbP4oFTWYEVshPKxivWSOw5yi4j4uzacVedlP851lVhJSpuuITlhpDsMIHHV+Enbd2XLiKc1dwde5jVPBvCsrWH6wga4rati4rNs+MyPGoSEHle6Di2gfzoHeGjRPHYfITwniAQm7h0t/cBKQcpYH3AHr/KeyPGEQ0ys3LWJJNFd/vJ9PEQRcgo76DNT0mTvRAATFY2VAkH8ePCX8/efpKC48nTIM1ZoY0CS4Mq/9FVCuJO1gw+4ewzOLkh1VMaFM68k3mMcQ526d5JkIZl1OkX58ureIevJAgLHih1uafhZ7XdXPLyvi9N9EWVA5lTQMmBW8nfhyVaDkvRt5rs5ZNvn+Cvx7wBn9DkIzs8BZ0S7tOQsv+QucRglJt+M8/EaT1v8V6W3dB/0HDT2LOibvKHwk6L5k7AwB2r8RFZB2jsWySqFlOXkukEaZCpZ/B+MtpiX1tYOF031PXh42ysqR5Yu136/eMY+X7X3VQTKdC9iIonmRCWWcCJu0AxaokXE5WqLZplD1oVxSR1ULtJVo6fNC2oMOVK4wSr16s3NwRQdvHm4j2FWKRX/9VYlrY6/Ck260htuqwkIoAdewE35IJcORgqX2OhqtBbRIg8=
