language: ruby
jdk:
- oraclejdk8
sudo: false
rvm:
- 2.3.1
install:
- rvm use 2.3.1
- gem install bundler
- bundle install
script: buildr clean package mcrt:publish_if_tagged
git:
  depth: false
env:
  global:
  - secure: qZ7LNxw14OEyZGwfH/vSPHhUvXkndTfrmzZfVrWWHi6zLAfmE5eoUINdj3r4BIevka7TD8NapMkJtp4nss8fjKItlGWCe2ccixs9M7gbyDkC/c0s3YmxLrUcRWrrrJgghvPUo9pqv6UXQrGx/2P4yJlXtAie8SeSAH+h3G/Of/W3Kc+ieH4o4b9cwICI1AfVVxmKv+Te0xW1U6qvU1QineXhx27OtcrsAhOq73Xuh6+My7fGDBz5tS8RzpYzEo88gNry8gWRCyohZT2ZTG9HW5Na6cPovh6JFIdH0CbRv2/HKIrWRtLVlv4e28N2cMx/pmFs2fPBpfQ/AIRzcziFtWqLXJQ0TYv6TFQTX6pMScZMlZ7pUJko9dEJDJqrUQ17sSlRt1ai+Wr/CEgCH76Xrr+7NC8JiiD0SxMylmOBpmcw1puyzTVV6t7gLE8JAyTvu1aX01N2Y2E9DVcP5sprA/Ka82RARgA5AJXzdS64IInn4LWlVKc8bg/mCJ9bFH6MAN0pjYk3stR9JO3NeSoQe9kp/YzhIiciOWqoYk0NW0LuxLFc1lSK3QD3bDhb9KMEjWWQAKkuEbPZ25tEZZ24peS6PO6HZ1bHkAvsST4iLFKsA8bR4QOwCoAKg4MzT6kFWgqPbkA0Qe5B4k2VdVm4eScMqoHEJJBn/K/oLbWZFz0=
  - secure: UrmGOnGBsDAQ2NVaggg2LI9kep6O9AoG8rhzhUQgcQQ9Cr7xX9aBwkWIyE9do37vhAqNdSbEQmSkKjorYy82wq/Dv3Ce7v6CllXLe3mfDULUVfU3/d5DegUWxcNMp2w+BOEdn/NbLkFndVKWUQz7zXcG5TMsQ7ukmRx9Nlm5JICdknt2Mbc7fEAnxSx41BZHUQenWq1uo9jCUnG3HDzk/zx9O5/7gmKH+dztMuS0d1StVnp3xmmK40w4WxS5J5kZcUzMCDFPyjeaSzdzlpSDUmaD2TRCP3aWm9jEjQCvfAzLHYqDXfo2kW2q9o3WvOjPvO7HkSjMXX5iabjoB1GMBmDEp4iQKgtnkNkOFye/c+hl82p5W1pAWPuBVqOp/g1jekZzYOFcu3m7gtbBSdkck4vjbH1t+mrQsLDBVCctZcje54txdbD3fjZlwqdV0hBuK+szRrMysQxEbhDEScfpcB2nQrIfVNPS98HwHMQVmWkSOgQED6k406XR0OoahcDV/qKLnW0/fcO217DoVVOpxcnVP1dBv+gf9oYOtt4tbVnHXsGaG/RZJAyg0kYWkp3P779z+m6bKH7mF8rkFaMs2zuoTwCxpjiDp2s6J7dUl7fuKnxPbjSIAbnQTysX8P05ciTkQqpyX8d9uu5ktlmZ27dx595ikmZrj25PzPhvag0=
  - secure: uUTp5wrO7KjBPFJCHRf2WKDkN44UJAoVEXI0Sr85P5q1sN3FnBdCCGic84jB5C3Ujwq9sTOmq3MzwBQtc691AmtdSmN2qxxlm4kg1NsDxedVMX1Em5i+T330aopWxvH3ptFgNc8h/aVhKzlVJK7ggms84mKh4+M1py2Eiwc/TfkIQCIH71McbNEbtfYCLk/77vN+ljr7054o67JuLfaPqq01oJ/bhE/jk0sAAP7En4DKVMiFPa4Lwj+WkS7ZQhWyK8xDlq9eI0/9rCgRXh0RvNnsXu2wPwq79Hml5rs5sBJs0t9KfneLZgapfx+XXNGgdw/CEA3xJRzsToxmrg3S00bpuAtVslEdDWZB+NxoerlRrfMqF2uhFhhLwjYQra8FGIOz+cjheZYfI38S45rnPYzVEM0cZ6qvFTvSK7hJyB0ux/T8elK0uNjWkMy7BKxh6mYzvOktmWcH0TXIH1UuyyNAxhZ7QWLInLFPudH0rF2JSgEpOSDsNTpdCT11yiNQ0tfWmUmV7Ma6Zuv2MoTjoc9/2wWi9fop/Yo2sONZoqfc9fe/99cHWzoAr+ezMxtqd7n0UX1T7e5ncnj6mPiVoRgBhfi4YmQi1aUPdWJW/ddP+YzfUEopJVAetnoiPJy2PWc7OV0vfkYSrqCep0Bs3lRyTRgZIfQDLVSQ+AMZINI=
before_install:
- openssl aes-256-cbc -K $encrypted_a796be79d2ec_key -iv $encrypted_a796be79d2ec_iv
  -in etc/secrets -out ../secrets.tar -d
