language: ruby
jdk:
- oraclejdk8
sudo: false
rvm:
- 2.3.1
before_install:
- openssl aes-256-cbc -K $encrypted_a796be79d2ec_key -iv $encrypted_a796be79d2ec_iv
  -in etc/secrets -out ../secrets.tar -d
- chmod 600 ../release.asc
- gpg --import ../release.asc
install:
- rvm use 2.3.1
- gem install bundler
- bundle install
script: buildr clean package mcrt:publish_if_tagged
git:
  depth: false
env:
  global:
  - secure: z19JRiBViG00ReXrXCQlXvdTXRyaJXBZmzHM7S1Hi10lntQxU10O8U6FGI1q0V+qwCsKt6ua+9TwcWOk9V+K0oEgJmrXqPBaeJcKI1krZw1rKzEHb/QBiwLhBhm3HNqf9HW1jZyJpWXrMFJWt3zAq8/fdpu7c3gPW2vdDKGie9DFVAaDn3lA/zI85vH8oRxPppHQahTcgF6cJUFBJSPOc/tTxRFR/l7StDvZ3mBJIlqlsV/rD2jtNeLKIWM3t3UX9WqSrkkiroNJzDiXlzUINFHX9323WFpJo+6XfVdkGsanJNjUTkFZ1cEB+GK03011pXSr1dXIglTrYXmlLj1ovcoAzd/oWeiKOxcGnuzpVQ1zYQu4iQMTg/3wSOHr9px2KMh0jkPkkfNeA8ockGgCzwN4u1SiByYUclcatVSyb8FgQFGEptTS+Q3VqFaeEht4VW5MaIFmyJOhyG8ozIljdlLhSrgW9s+GWTLkDtEg0IbDftDp91K0xGbV1MX2I5GSgMEoz5xJiPDBPscAg+yzuSO4IdkdiOoFHL9lrHAv17p3DDhul0/zPMmIgz4d/NnvSmR3ubPIH4xs1v0flmKB3iMtrUj3pVsAMi8Og4294FHsqEmoM8ea0z/T/fdoOQ+kd2xlfPZZZzs5yXDYI4B/v6Mgxz8+Vt5u30xwMbb5Vv8=
  - secure: kRoLOr9DqxKpe5w9Tg0+E0pEpCfUt6pIorFaoL3LkMBdTYvKaKyTvWgJSdOnRwdcGqmI6OAQlOzPBZ9rmE/O+sGGSpysS9WERz3ts0kZUxb2wGGfaJtCPDvmeRFTISMQCtNSJ+sG6uw3mE268Y4mxiDWJqf3nZoCDgr7KcqFS5vlvRUfRDPh6BZ+oRzki16NvzexhgZzrE+iIZBTP8KU1xxHnjfGZMNTEFgKobuY69n/w9KATArnsrb5B3Vz33LZmU1myp4YiyNkN7YZ3NQFj2sZpHOy+7Z8yEBI/RHZC2smO2WuMxi0az0M50axMlhZCweznWNlZapHtn/lZe/p8/i3YOvTLTfSe2V5JlfRVNcSUjHIdEKyXa4Xig9Cl5raBIkVoIXgRfPw+pojxsFPS60TIVk5KJEYm0blPZ2/5qVLiQ+Eu6XKVoZOCnC6fopUTfI3iFhWMbUvBlBYWY5YugXOCCGrp0CENTYHG1HhC7Hh7fCB1P5tF/zCHJm6o8N4IIzbuQI44GBgREkwUAvEdu8Fw96ovvo8l1zxChCIpiVrLU1VZ0WGBagm/6fLDWFQYJta5Cgl3YeRDq7pVGUgTPby1O20IA6VVmt+Orz5gds9eiTjGIuTxD44fslWBnB1tRGO4a7RPilRqZofDpCddYqqeLHTLqdmQo7SSIicZPU=
  - secure: TUxzMPmuS2U1dvK/ykYLRCc8dv1igNUUN9DgQ1WN3AQxUUx6fD9YZ/ymKMdQC2HDEOxq84MNwaxEjMsnCZf3xUKhMUGOFaLolK2sn7UpcfuIc8xtnng6FD6Pl9hAWKgaPcFobinIgO2c3dahLXnmeLfvjhi36J4W8OtyVWXaIy/KLAn55lkgc/KiVKqFjLyFVqukMtwIwyLNcoOHhsxatvW1EVgUe1U06D3sqhwrvOGO4SOumOZQ6Ns3yr01xwIvEPJICTEUHJcQDxL3vdTyO433BrTCqmVzqpEXsoMPuu3oYtyH3XKQ/twktsSqDd4krQaesGzosau05IwMelt2j0jYPguk7d2nhOWlm3EOsC579uEuXrZ5kTdku6iWfEDXO4S8BORLtrgm+bhXGXaG82FckPtpfgUh5l6xfrxJ6u8IS9/7YERr+XZpmKQ2866Udw4RPHKm92NdBbIDT8qr8SG0tj6U/rGee0Bwulw2oQlZlSnbXQpFlIbO6anN/Pp5AKF6v61DwpbixgOyF/VtRuRgbiEh4YYoOrq3Xqo8DCkmfaTXFvXC6n4asRbcVYeM4QylnhXVTtYc3YPZvE2kCU18gUn7GdYEWTKrhGDrMchsPihD2X6fAe3tFoFILauD79h6tXlWS8Vdg5OViI3APEEL4rONvp3z/N7Wv1FQQO4=
